sudo: true
language: python
python:
    - "2.7"

env:
    matrix:
      - TOXENV=py27-dj15
      - TOXENV=py27-dj16
      - TOXENV=py27-dj17
      - TOXENV=py27-dj18
      - TOXENV=py27-dj19

install:
    - pip install tox
script: tox
